### ISSUE TITLE
[BUG] Photo Booth icon not appearing [iOS 12.1.3, lofi theme]

### ISSUE THREAD

**Issue by Goodgamer78** [itsnebulalol/minimalize-issue-tracker#16]
**Describe the bug**
The Photo Booth icon will not appear on any picture preset.

**Screenshots**
![image](https://user-images.githubusercontent.com/57049869/132912993-3649ef9c-d085-4cc1-9093-7faf3c9ed5fb.png)

**Device info (please complete the following information):**
 - Device: [iPad Mini 2]
 - OS: [iOS 12.1.3]

**Additional context**

**Comment by itsnebulalol** [comment]
Will be fixed in the next release soon™️
