### ISSUE TITLE
[REQUEST] 5 Icon requests

### ISSUE THREAD

**Issue by ZonatedTech** [itsnebulalol/minimalize-issue-tracker#24]
![92851D05-2685-49FB-AE85-9779FD3A142E](https://user-images.githubusercontent.com/63753030/133958834-95beba4a-faea-471f-8e9c-a4ff1aab5f91.png)

Hey, could you possibly sometime make these five applications on the bottom themed? (obviously the only five apps that aren’t themed on the bottom)  
I would highly appreciate if you did, either way great work on the theme!

**Comment by itsnebulalol** [comment]
Will all be included in the next release
