### ISSUE TITLE
[REQUEST] Windscribe VPN

### ISSUE THREAD

**Issue by Goodgamer78** [itsnebulalol/minimalize-issue-tracker#6]
**com.windscribe**
Please put the bundle ID of the app here. You may find the bundle ID from Bundely on Spark’s repo. Not jailbroken? Use [this online tool](https://offcornerdev.com/bundleid.html) to fetch bundle IDs from apps on the App Store.

**Repo the app is on (for jailbroken apps)**
If the app can only be installed jailbroken, put the **official** repo of the app here.

**Comment by itsnebulalol** [comment]
Will be included in the next release
