### ISSUE TITLE
[REQUEST] Icon requests

### ISSUE THREAD

**Issue by breadcat0314** [itsnebulalol/minimalize-issue-tracker#8]
Icon 1: 
Apollo for Reddit
com.christianselig.Apollo-large.png 

icon 2:
Floatplane Media
com.floatplane.floatplane-large.png

icon 3:
CARROT Weather
com.grailr.CARROTweather-large.png

**Comment by itsnebulalol** [comment]
Finished all of them, will be included in the next release.

Next time, please make seperate issues.
